CATEGORY=	itgrund/assignments
FILES=		internet.tex ../../literature.bib
DOCUMENTS=	internet.pdf
 
PACKAGE=		internet-src
PACKAGE_FILES=	${FILES}

PUB_FILES=		${DOCUMENTS}

internet.pdf: internet.tex ../../literature.bib

include miun.course.mk
include miun.package.mk
