SERVER=		secure.itm.miun.se
PUBDIR=		/home/danbos/www/pub
CATEGORY=	itgrund/assignments
FILES=		assgn-install.tex ../../itgrund.bib
DOCUMENTS=	assgn-install.pdf

all: ${DOCUMENTS}

include miun.docs.mk
