DOCUMENTS=	sftp.pdf
FILES=		sftp.tex ../../literature.bib rfc.bib
CATEGORY=	itgrund/assignments

PACKAGE=		sftp-src
PACKAGE_FILES=	${FILES}

PUB_FILES=		${PACKAGE}.tar.gz ${DOCUMENTS}

sftp.pdf: ${FILES} rfc.bib

include miun.course.mk
include miun.package.mk
