SERVER=		secure.itm.miun.se
PUBDIR=		/home/danbos/www/pub
CATEGORY=	itgrund/assignments
FILES=		assgn-sftp.tex ../../itgrund.bib
DOCUMENTS=	assgn-sftp.pdf

assgn-sftp.pdf: assgn-sftp.tex rfc.bib

include miun.docs.mk
