DOCUMENTS=	latex.pdf
FILES=		latex.tex ../../literature.bib
CATEGORY=	itgrund/assignments

PACKAGE=		latex-src
PACKAGE_FILES=	${FILES}

PUB_FILES=		${PACKAGE}.tar.gz ${DOCUMENTS}

latex.pdf: latex.tex ../../literature.bib

include miun.course.mk
include miun.package.mk
