CATEGORY=	itgrund/lectures
FILES=		shell.tex ../../literature.bib
DOCUMENTS=	shell.pdf

PACKAGE=		shell-src
PACKAGE_FILES=	${FILES}

PUB_FILES=	${PACKAGE}.tar.gz ${DOCUMENTS}

shell.pdf: shell.tex ../../literature.bib

include miun.course.mk
include miun.package.mk
