SERVER=		secure.itm.miun.se
PUBDIR=		/home/danbos/www/pub
CATEGORY=	itgrund
FILES=		literature.tex ../itgrund.bib welcome.tex studyguide.tex \
			kursplan.pdf
DOCUMENTS=	literature.pdf welcome.pdf studyguide.pdf

include miun.docs.mk
