CATEGORY=	itgrund
FILES=		literature.tex ../itgrund.bib welcome.tex studyguide.tex \
			kursplan.pdf
DOCUMENTS=	literature.pdf welcome.pdf studyguide.pdf

literature.pdf: literature.tex ../itgrund.bib
welcome.pdf: welcome.tex kursplan.pdf
studyguide.pdf: studyguide.tex ../itgrund.bib

include miun.course.mk
