SUBDIR= 	install
SUBDIR+= 	terminal
#SUBDIR+= 	linux
SUBDIR+= 	python
#SUBDIR+= 	latex
SUBDIR+= 	computer
#SUBDIR+= 	internet
#SUBDIR+= 	security
#SUBDIR+= 	sftp
SUBDIR+= 	present

include miun.subdir.mk
