# $Id$

COURSE=		DT001G_27067_HT12
REWRITES=	"s/Godkänd(G)/P/g" \
			"s/Underkänd(U)/F/g" "s/Komplettering(Fx)/Fx/g" \
			"s/Assignment:P0Projekt/R105/g" \
			"s/Assignment:P1Projektpresentation/P105/g" \
			"s/Assignment:L[0-9]*\([A-Za-z]*\)/I105 \1/g"

include miun.results.mk
