CATEGORY=	itgrund/assignments
FILES=		terminal.tex ../../literature.bib
DOCUMENTS=	terminal.pdf

#PACKAGE=		terminal-src
#PACKAGE_FILES=	${FILES}
#
#PUB_FILES=		${PACKAGE}.tar.gz ${DOCUMENTS}

terminal.pdf: ${FILES}

include miun.course.mk
#include miun.package.mk
